### ISSUE TITLE
Unable to manually manage Images

### ISSUE THREAD

**Issue by turowicz** [takuya-takeuchi/FaceRecognitionDotNet#15]
I get images from a webcam stream using OpenCV. I need to be able to load them up without using any disk files and use them in C#. So far I've been working with python and that feature is available there.

Unfortunately the constructor of `Image` is private in https://github.com/takuya-takeuchi/FaceRecognitionDotNet/blob/master/src/FaceRecognitionDotNet/Image.cs#L23

Ideally it would be nice to be able to create a `Image` from `byte[]`

**Comment by takuya-takeuchi** [comment]
You can use FaceRecognition.LoadImage.

**Comment by turowicz** [comment]
@takuya-takeuchi  I'm having trouble loading it from RGB
```
var frame = GetOpenCvMat();
var data = frame.ToBytes(".jpg",  new ImageEncodingParam(ImwriteFlags.JpegQuality, 90));
var image = FaceRecognition.LoadImage(data, frame.Height, frame.Width, 3);
```

The exception

```
Exception has occurred: CLR/System.ArgumentOutOfRangeException
Exception thrown: 'System.ArgumentOutOfRangeException' in DlibDotNet.dll: 'Specified argument was out of the range of valid values.'
   at DlibDotNet.Matrix`1..ctor(Byte[] array, Int32 row, Int32 column, Int32 elementSize)
   at FaceRecognitionDotNet.FaceRecognition.LoadImage(Byte[] array, Int32 row, Int32 column, Int32 elementSize) in /Users/wojtek/Workspace/facedotnet/src/FaceRecognitionDotNet/FaceRecognition.cs:line 374
```

**Comment by turowicz** [comment]
also failing:

```
var image = FaceRecognition.LoadImage(frame.ToBytes(), frame.Rows, frame.Cols, 3);
```

**Comment by turowicz** [comment]
also failing...

```
var data = frame.ToBytes(".bmp");
var image = FaceRecognition.LoadImage(data, frame.Rows, frame.Cols, 3);
```

Probably on this assertion

```
if (array.Length != row * column * elementSize)
    throw new ArgumentOutOfRangeException($"{nameof(array)}.Length should equalt to {nameof(column)}x{nameof(column)}*{nameof(elementSize)}.");
```
but the size is almost there:

```
data.Length
2239542

frame.Rows*frame.Cols*3
2239488
```

**Comment by turowicz** [comment]
OK this is how it's meant to be done:
https://github.com/takuya-takeuchi/DlibDotNet/blob/5d25c234b7d8c9de10071c4279e2ded65a3fbff5/examples/WebcamFacePose/Program.cs#L51
