### ISSUE TITLE
CudaException code 77

### ISSUE THREAD

**Issue by turowicz** [takuya-takeuchi/FaceRecognitionDotNet#19]
I'm getting the following error:

```
      CUDA Error Lib:libDlibDotNet.Native.Dnn.so Code:77 Driver:10000 Runti,:10000 Message:Exception of type 'DlibDotNet.CudaException' was thrown..
fail: People.Service[0]
      Exception of type 'DlibDotNet.CudaException' was thrown.
DlibDotNet.CudaException: Exception of type 'DlibDotNet.CudaException' was thrown.
   at DlibDotNet.Dnn.Cuda.ThrowCudaException(ErrorType error)
   at DlibDotNet.Dnn.LossMmod.Operator[T](IEnumerable`1 images, UInt64 batchSize)
   at FaceRecognitionDotNet.Dlib.Python.CnnFaceDetectionModelV1.Detect(LossMmod net, Image image, Int32 upsampleNumTimes)
   at FaceRecognitionDotNet.FaceRecognition.RawFaceLocations(Image faceImage, Int32 numberOfTimesToUpsample, Model model)
   at FaceRecognitionDotNet.FaceRecognition.FaceLocations(Image image, Int32 numberOfTimesToUpsample, Model model)+MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at People.Common.Services.IdentificationService.IdentifyAsync(Guid applicationId, Mat frame, Double tolerance) in /app/src/People.Common/Services/IdentificationService.cs:line 70
   at People.Common.Pipeline.Blocks.IdentificationBlock.CheckIdentityAsync(Result result) in /app/src/People.Common/Pipeline/Blocks/IdentificationBlock.cs:line 54
```

Any ideas what this means? Googling the error code

**Comment by turowicz** [comment]
@takuya-takeuchi have you had such problems?

**Comment by turowicz** [comment]
size: 1920x1080 or 1440x800 (depends on source)
numberOfTimesToUpsample: 0

**Comment by turowicz** [comment]
The error starts to appear after ~1h of video processing (frame by frame)

**Comment by turowicz** [comment]
I'm investigating memory leaks.

**Comment by turowicz** [comment]
@takuya-takeuchi aren't you forgetting to dispose `faceLandmark` object?

https://github.com/takuya-takeuchi/FaceRecognitionDotNet/blob/master/src/FaceRecognitionDotNet/FaceRecognition.cs#L256

**Comment by takuya-takeuchi** [comment]
@turowicz 
You are right. Thank you!!
And there are same issues in other line.

**Comment by takuya-takeuchi** [comment]
@turowicz
Could you try nuget 1.2.3.6 package?
If you have any issue, please let me know!!! Thank you!!

**Comment by turowicz** [comment]
@takuya-takeuchi I will test as soon as possible.

**Comment by turowicz** [comment]
@takuya-takeuchi I haven't seen this error for a while now. I have started getting error `74` though. Investigating. Will create separate issue if real problem.

**Comment by turowicz** [comment]
@takuya-takeuchi unfortunately the error still exists.

**Comment by turowicz** [comment]
Actually I think this is due to a problem on my end. Only one of two PCs has this error. It's Alienware Aurora R7 running Ubuntu 18.04.

**Comment by turowicz** [comment]
BTW memory usage is much better after the memory leak fix.

**Comment by takuya-takeuchi** [comment]
> Alienware Aurora R7 running Ubuntu 18.04

I have same machine and I boot Ubuntu 18.04 from usb memory.
My R7 has 1080 (not Ti).

I may be reproduce same issue. Could you tell me Nvidia component version - CUDA and cuDNN?
