### ISSUE TITLE
AWS Lambda Error Unable to load shared library 'DlibDotNetNativeDnn' or one of its dependencies

### ISSUE THREAD

**Issue by zwalten** [takuya-takeuchi/FaceRecognitionDotNet#241]
Getting the following error after deploying to AWS Lambda. It works fine when running in Visual Studio using the Mock Lambda Test Tool on Windows 11

System.TypeInitializationException: The type initializer for 'DlibDotNet.NativeMethods' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'DlibDotNetNativeDnn' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libDlibDotNetNativeDnn: cannot open shared object file: No such file or directory
   at DlibDotNet.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at DlibDotNet.NativeMethods.matrix_new4(MatrixElementType matrixElementType, UInt32 templateRows, UInt32 templateColumns, IntPtr& ret)
   at DlibDotNet.Matrix`1.CreateTemplateParameterizeMatrix(UInt32 templateRows, UInt32 templateColumns)
   at FaceRecognitionDotNet.FaceRecognition.LoadFaceEncoding(Double[] encoding)

**Comment by zwalten** [comment]
Got it to work using docker
