### ISSUE TITLE
Missing entry point named 'dnn_cuda_cudaDriverGetVersion' in DLL 'DlibDotNetNativeDnn'

### ISSUE THREAD

**Issue by MitchVonk** [takuya-takeuchi/FaceRecognitionDotNet#28]
I'm trying to run FaceRecognitionDotNet with Cuda, but I think it seems that I miss some dll files. 

The following Exception occurs:

Unhandled Exception: System.EntryPointNotFoundException: Unable to find an entry point named 'dnn_cuda_cudaDriverGetVersion' in DLL 'DlibDotNetNativeDnn'.
   at DlibDotNet.NativeMethods.dnn_cuda_cudaDriverGetVersion(Int32& version)
   at DlibDotNet.Dnn.Cuda.ThrowCudaException(ErrorType error)
   at DlibDotNet.Dnn.LossMmod.Operator[T](IEnumerable`1 images, UInt64 batchSize)
   at FaceRecognitionDotNet.Dlib.Python.CnnFaceDetectionModelV1.Detect(LossMmod net, Image image, Int32 upsampleNumTimes)
   at FaceRecognitionDotNet.FaceRecognition.FaceLocations(Image image, Int32 numberOfTimesToUpsample, Model model)+MoveNext()
   at FaceRecognitionDotNet.FaceRecognition.FaceEncodings(Image image, IEnumerable`1 knownFaceLocation, Int32 numJitters)+MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at FaceDetection.GetDetections(String imageFilePath, FileType fileType, DetectionType detectionType)
   at UseFaceDetection.Program.Main(String[] args) in C:\Users\Documents\FaceDetection\FaceDetection\Program.cs:line 45

I obtained the following dll files for cuda: cublas64_92.dll, cudnn64_7.dll, curand64_92.dll and cusolver64_92.dll. (Found in requirements at: https://nugetmusthaves.com/Package/DlibDotNet-WithCUDA)

I figure I am missing or using a wrong reference needed for DlibDotNetNativeDnn. Is there a list of needed Cuda libraries or anything else I might be missing?

**Comment by MitchVonk** [comment]
![image](https://user-images.githubusercontent.com/31694193/53475765-133d2300-3a71-11e9-9e24-50df8c568602.png)

I think it is looking for the wrong method? The function in my dll is: cuda_cudaDriverGetVersion instead of dnn_cuda_cudaDriverGetVersion

**Comment by takuya-takeuchi** [comment]
you are right.
but this problem is not what you failed to execute dll.
because what getcudaversion is called is that your apps faced to cuda error rather than dlibdotnet.
I'll fix it and you could get correct error information.
