### ISSUE TITLE
Inner Exception: System.EntryPointNotFoundException: Unable to find an entry point named 'Win32LoadLibrary' in DLL 'kernel32'.

### ISSUE THREAD

**Issue by ingmoyete** [takuya-takeuchi/FaceRecognitionDotNet#52]
Hi,
I am trying to run the test "TestFaceLandmarksSmallModel", everything works fine till I reach the ShapePredictor.Deserialize method where an exception is thrown saying precictor is zero. The output displays the following messsage:

Inner Exception: System.EntryPointNotFoundException: Unable to find an entry point named 'Win32LoadLibrary' in DLL 'kernel32'.
   at DlibDotNet.WindowsLibraryLoader.Win32LoadLibrary(String dllPath)
   at DlibDotNet.WindowsLibraryLoader.LoadLibraryRaw(String dllName, String baseDirectory) in C:\Users\david.alcocer\Source\Repos\FaceRecognitionDotNet\DlibDotNet\src\DlibDotNet\PInvoke\WindowsLibraryLoader.cs:line 214
Exception thrown: 'System.Exception' in DlibDotNet.dll

Screen shot of exception:
![image](https://user-images.githubusercontent.com/24899146/59905578-e5586180-9406-11e9-8a7f-7cb8bd706862.png)

Thanks.

**Comment by takuya-takeuchi** [comment]
Thank you for reporting issue.
I'm glad you report issue with detail information.[

I believe https://github.com/takuya-takeuchi/DlibDotNet/issues/111 is same issue.

This issue is DlibDotNet's.
I guess the following definition is wrong.

````
[DllImport("kernel32", CallingConvention = CallingConvention.Winapi, SetLastError = true, BestFitMapping = false, ThrowOnUnmappableChar = true)]
        private static extern IntPtr Win32LoadLibrary(string dllPath);
````

It could be 

````
[DllImport("kernel32", EntryPoint = "LoadLibrary", CallingConvention = CallingConvention.Winapi, SetLastError = true, BestFitMapping = false, ThrowOnUnmappableChar = true)]
        private static extern IntPtr Win32LoadLibrary(string dllPath);
````
